# Generated by Django 4.0.4 on 2022-05-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('branche', models.CharField(choices=[('FS', 'FullStack'), ('DS', 'DataScience'), ('AWS', 'Amazon Web Service')], default='FS', max_length=20)),
                ('Location', models.CharField(choices=[('TR', 'Turkey'), ('ABD', 'America'), ('Bul', 'Bulgaristan')], default='TR', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Todos',
            },
        ),
    ]
